### PR TITLE
identify bars as non_economic items

### LINKED ISSUE #1699: Buildingplan can't match metal bars as construction materials
See initial investigation in #1689

The issue is that if you try to build something that requires a building_material item, buildingplan never chooses a metal bar, even when it should. For example, if you try to build a track stop in buildingplan and set the material filter to 'metal', it will never choose an iron bar, even if that is the only building material available.

There are two separate bugs that need to be fixed. The first is in [Materials.cpp:516](https://github.com/DFHack/dfhack/blob/develop/library/modules/Materials.cpp#L516) in
`void MaterialInfo::getMatchBits(df::job_item_flags2 &ok, df::job_item_flags2 &mask)`:

`TEST(non_economic, !inorganic || !(ui && vector_get(ui->economic_stone, index)));`

It looks like iron bars should get "non_economic" set.

The second bug is that buildingplan's ItemFilter itself fails to match an iron bar as a valid metal material. I haven't tracked down the root cause for that one yet.

### PR DESCRIPTION
**Pull request by myk002**
Fixes #1699

allows MaterialInfo to match metal bars as a building material. This allows metal bars to be used for construction in buildingplan.

### CODE REVIEW

**Comment by myk002** [comment]
if this approach is accepted, I'll update docs in this PR as well

File: library/include/modules/Job.h [hunk 1]
```diff
@@ -102,7 +102,7 @@ namespace DFHack
                                          int filter_idx = -1, int insert_idx = -1);
 
         DFHACK_EXPORT bool isSuitableItem(df::job_item *item, df::item_type itype, int isubtype);
-        DFHACK_EXPORT bool isSuitableMaterial(df::job_item *item, int mat_type, int mat_index);
+        DFHACK_EXPORT bool isSuitableMaterial(df::job_item *item, int mat_type, int mat_index, df::item_type itype = df::item_type::NONE);
```
Comment (lethosor) [inline library/include/modules/Job.h:105]: `job_item` objects have an `item_type` field - would that work, or is it different / not set in the case you care about?

File: library/include/modules/Materials.h [hunk 2]
```diff
@@ -78,6 +78,7 @@ namespace DFHack
 
         int16_t type;
         int32_t index;
+        df::item_type itype;
```
Comment (lethosor) [inline library/include/modules/Materials.h:81]: I'm a bit reluctant to introduce item-specific state in a material-specific class (I think this is basically what you brought up in https://github.com/DFHack/dfhack/issues/1699#issuecomment-726472912). The only place I see this state used is in Job::isSuitableMaterial(), specifically when the MaterialInfo is passed to `iinfo.matches(*item, &minfo);`

Would it be possible to make `ItemTypeInfo::matches()` take the item type instead of storing it in `MaterialInfo`? Possibly even better, `matches()` already takes a `job_item`, which has a `item_type` field per above - if this field is already set to the correct value, that could work (but I'm not sure if it is).

**Review by lethosor — COMMENTED** [review]
I left some comments on what I think might be a possible alternative.

----

Another, potentially less-useful possibility I thought of when replying to #1699, before taking a closer look at this PR:

Would it make sense to change the non_economic flag around here? Or is that too early/late?
https://github.com/DFHack/dfhack/blob/fce10e598e61634824fd1a851e8dbc666c648931/library/modules/Items.cpp#L348-L352

This comment seems relevant, although I'm not sure where exactly the flag is being checked: https://github.com/DFHack/dfhack/blob/fce10e598e61634824fd1a851e8dbc666c648931/library/modules/Items.cpp#L327-L329

From what I've gathered, `xmask` indicates flags that should _not_ be checked in certain cases, but I'm not sure if that works here.

File: library/include/modules/Materials.h (hunk 2 above)
Comment (lethosor) [reply library/include/modules/Materials.h:81]: I did some investigating on my end, and it looks like ItemTypeInfo::matches is getting a job_item with `item_type = NONE` after creating a metal bar with `createitem BAR IRON`, enabling bars with `b-C-f-G-r`, and planning a new floor. Tables do seem to result in `item_type = TABLE` being set. I probably misunderstood the purpose of job_item - I'm guessing its fields make up more of a template and less of a concrete item.

File: library/modules/Job.cpp [hunk 3]
```diff
@@ -608,15 +608,16 @@ bool Job::isSuitableItem(df::job_item *item, df::item_type itype, int isubtype)
...
+    df::job_item *item, int mat_type, int mat_index, df::item_type itype)
 {
     CHECK_NULL_POINTER(item);
 
     if (mat_type == -1 && mat_index == -1)
         return true;
 
     ItemTypeInfo iinfo(item);
-    MaterialInfo minfo(mat_type, mat_index);
+    MaterialInfo minfo(mat_type, mat_index, itype);
```
Comment (lethosor) [inline library/modules/Job.cpp:620]: Since `job_item.item_type` doesn't seem to be as useful as I had hoped, I think an alternative "clean" solution might be to pass `itype` to `matches()` below instead of storing it in `MaterialInfo`. (I think this is the only place where the stored `itype` is actually relied on, but I could be missing something - most of the other additions appear to just be passing it along.)

**Comment by myk002** [comment]
I think passing the item type to matches() is a good idea. Will rejigger.

For reference, the job_item is the filter returned from buildings.lua. table has the item type set because it is set in the filter. Any construction material can be any of several types, so the filter doesn't set a type, just flags describing the required properties.

**Comment by myk002** [comment]
> https://github.com/DFHack/dfhack/blob/fce10e598e61634824fd1a851e8dbc666c648931/library/modules/Items.cpp#L327-L329
> 
> From what I've gathered, `xmask` indicates flags that should _not_ be checked in certain cases, but I'm not sure if that works here.

I'm seeing a lot of similarities between Items.cpp and Materials.cpp. They both check the same flags, but Items.cpp seems to be better at it. In particular, 
https://github.com/DFHack/dfhack/blob/fce10e598e61634824fd1a851e8dbc666c648931/library/modules/Materials.cpp#L447-L463 does pretty much the same check, but without an xmask. The solution here appears to be to route itype to *that* matches() function and introduce an xmask for job_item_flags2. An even better solution might be to unify related logic in Items.cpp and Materials.cpp, but that's a larger issue.

**Comment by myk002** [comment]
the only script usage of getSuitableMaterial() that I found is in gui/workshop-job. I'll update that script in a separate PR.

**Comment by myk002** [comment]
I added the change to isSuitableMaterial() to the API section, though it might also belong in the 'fixes' section..

**Review by lethosor — APPROVED** [review]
Looks like it works on my end now!

Thanks for clarifying the job_item usage. As for the changelog, the API section is fine since that's the only user-facing change since r3 (constructions weren't plannable before).

File: library/modules/Job.cpp [hunk 4]
```diff
@@ -605,10 +605,11 @@ bool Job::isSuitableItem(df::job_item *item, df::item_type itype, int isubtype)
     ItemTypeInfo iinfo(itype, isubtype);
     MaterialInfo minfo(item);
 
-    return iinfo.isValid() && iinfo.matches(*item, &minfo);
+    return iinfo.isValid() && iinfo.matches(*item, &minfo, true, itype);
```
[the remark this answers is not in the document]
Comment (myk002) [reply library/modules/Job.cpp:608]: sorry, yes, intentional, but not for this PR. I'll revert it here and discuss why I think this is a good idea in a future PR.

File: docs/changelog.txt [hunk 5]
```diff
@@ -50,7 +50,7 @@ changelog.txt uses a syntax similar to RST, with a few special sequences:
 
 ## API
 - `buildingplan`: added Lua interface API
-- `job-module`: add item type param to dfhack.job.isSuitableMaterial() so the non_economic flag can be properly handled (it was being matched for all item types instead of just boulders)
+- add item type param to dfhack.job.isSuitableMaterial() so the non_economic flag can be properly handled (it was being matched for all item types instead of just boulders)
```
Comment (lethosor) [inline docs/changelog.txt:53]: We could add an anchor like `.. _job-module:` to `Lua API.rst` (although it would only document what's exposed to Lua). The reason I don't usually do this is that changelogs are essentially reused verbatim as Markdown for GitHub and Reddit, causing anything in backticks to show up as code. It's fine for tools like `buildingplan` but could be weird or confusing for `job-module` to show up as-is. (I manually corrected the quickfort user guide link for r3, but a longer-term solution would be to actually generate proper markdown links somehow.)

An alternative could be to start with ``dfhack.job.isSuitableMaterial()`` (in double backticks, so it's not an RST link). Doesn't need to be part of this PR - I plan to work on changelog-related documentation before r4, so I'll do it then.

File: library/modules/Job.cpp (hunk 4 above)
[the remark this answers is not in the document]
Comment (lethosor) [reply library/modules/Job.cpp]: Ok, sounds good, and floors with metal bars still work with that reverted.

File: docs/changelog.txt (hunk 5 above)
Comment (myk002) [reply docs/changelog.txt:53]: ok, I'll use the double backtick approach in the future in situations like this. Thanks!
