### PR TITLE
PluginManager improvements

### LINKED ISSUE #666: Plugin system-related issues
- [x] `plug` only lists plugins with commands
- [x] The name passed to `DFHACK_PLUGIN` does not have to match the plugin filename (RemoteFortressReader vs. remotefortressreader, for example), allowing for possible name collisions
- [x] Plugins that don't exist on startup can't be loaded later
- [x] Plugins that are deleted after startup produce an unhelpful error message when reloaded (different from the message for other nonexistent plugins)
- [x] `ls` gives no feedback for unloaded plugins
- [x] `load`/`unload`/`reload` give no feedback for broken plugins

### PR DESCRIPTION
**Pull request by lethosor**
* load/unload/reload are no longer restricted to plugins that exist
  on startup
* Names passed to DFHACK_PLUGIN must match the plugin's filename
  (see remotefortressreader vs RemoteFortressReader, counters vs probe)
* `plug` output lists all plugins and state/command information
* Deleted plugins can be reloaded again if they are replaced
* load/unload/reload don't fail silently with broken plugins
* Built-in commands are recognized internally (e.g. "help help"
  does not display "help is not a recognized command"), although help
  for them is not yet implemented
* New command: `type` (bash-like) - shows where/how a command is
  implemented
* `plug` can accept multiple plugin names
* `ls` displays more information about unloaded/unrecognized plugins
* `load all` changed to `load -all` (or `load --all`, `load -a`, ...)

Closes #666

### CODE REVIEW

**Comment by PeridexisErrant** [comment]
Does this make fixing  #412 easier?  It sounds somewhat similar, to me.

**Comment by lethosor** [comment]
This really only affects plugins, and I didn't change how `ls` with no arguments works (just the `ls PLUGIN` form).

File: library/Core.cpp [hunk 1]
```diff
@@ -485,6 +485,43 @@ static std::string sc_event_name (state_change_event id) {
...
+    if (cmd == "ls" ||
+        cmd == "help" ||
+        cmd == "type" ||
+        cmd == "load" ||
+        cmd == "unload" ||
+        cmd == "reload" ||
+        cmd == "enable" ||
+        cmd == "disable" ||
+        cmd == "plug" ||
+        cmd == "type" ||
```
Comment (PeridexisErrant) [inline library/Core.cpp]: "type" is duplicated here.
