### PR TITLE
Fix memory return calling convention in ruby bindings

### LINKED ISSUE #1209: Ruby codegen can't handle vmethods that return std::string's
enabler::GetKeyDisplay() is new in https://github.com/DFHack/df-structures/commit/559c23baa06f68d62a0ba674669389273bfcfb97#diff-cee8bfd3ccf90f6603c9dc081d54d943

This produces a `vmethod unkret DFHack.vmethod_call(self, 0, InterfaceKey.int(arg0))` message in ruby/codegen.pl, and it looks like the generated function calls `rb_dfget_rtti_classname`, which can crash. The output below is from 64-bit OS X 0.44.03; note that the returned value for "2" is 0x101ee35c0, which is the address of `enabler`.
```
[DFHack]# rb puts df.enabler.GetKeyDisplay 2
4327355840
[DFHack]# rb puts df.enabler.GetKeyDisplay 3
(segfault)
```

### PR DESCRIPTION
**Pull request by suokko**
Calling convention for memory return is that caller allocates (in stack)
memory to hold returned object. Then caller passes the pointer to callee
as implicit first parameter.

references:
https://github.com/hjl-tools/x86-psABI/wiki/X86-psABI
https://msdn.microsoft.com/en-us/library/7572ztz4.aspx

Fixes #1209

### CODE REVIEW

File: plugins/ruby/codegen.pl [hunk 1]
```diff
@@ -534,6 +539,18 @@ sub render_class_vmethod_ret {
         };
         push @lines_rb, "end._at(ptr) if ptr != 0";
     }
+    elsif ($retmeta eq 'primitive')
```
Comment (BenLubar) [inline plugins/ruby/codegen.pl]: is this condition inverted?

Comment (BenLubar) [reply plugins/ruby/codegen.pl]: is stl-string a primitive? I would assume no, but I might be wrong.

**Comment by suokko** [comment]
lower-1.xslt has following:
         <prim-type ld:meta='primitive' ld:subtype='stl-string'/>

File: plugins/ruby/codegen.pl (hunk 1 above)
Comment (lethosor) [reply plugins/ruby/codegen.pl]: I didn't think stl-strings were considered primitives in df-structures, at least, but I could be wrong about that.

Comment (suokko) [reply plugins/ruby/codegen.pl]: lower-1.xslt defines stl-string and stl-fstream to be primitive

Comment (lethosor) [reply plugins/ruby/codegen.pl]: Oops, I was looking at the diff and didn't see your other comment (below here).
