### PR TITLE
Fix makeButtonLabelText pen tables

### LINKED ISSUE #4621: `makeButtonLabelText` not handling pen tables
Using example 1 from the docs throws an error due to setting the `pens` and `pens_hover` variables to pen tables, which aren't currently being handled.

```
widgets.Label{
    text=widgets.makeButtonLabelText{
        chars={
            ' Activate ',
            ' civilian ',
            '  alert   ',
        },
        pens={fg=COLOR_BLACK, bg=COLOR_LIGHTRED},
        pens_hover={fg=COLOR_WHITE, bg=COLOR_RED},
    },
    on_click=sound_alarm,
},
```
image
image

### PR DESCRIPTION
**Pull request by tatoyoda600**
Fixes #4621 

Allows for passing in values such as:
```
pens={
    {{fg=COLOR_YELLOW, bg=COLOR_LIGHTRED},{fg=COLOR_BLUE, bg=COLOR_DARKGRAY}},
    {{fg=COLOR_BLACK, bg=COLOR_LIGHTRED},{fg=COLOR_BLACK, bg=COLOR_LIGHTRED}},
},
```
```
pens={
    {{fg=COLOR_YELLOW, bg=COLOR_LIGHTRED},{fg=COLOR_BLUE, bg=COLOR_DARKGRAY}},
    {fg=COLOR_BLACK, bg=COLOR_LIGHTRED},
},
```
```
pens={fg=COLOR_BLACK, bg=COLOR_LIGHTRED},
```

### CODE REVIEW

File: library/lua/gui/widgets.lua [hunk 1]
```diff
@@ -1708,9 +1708,9 @@ end
 local function get_button_token_base_pens(spec, x, y)
     local pen, pen_hover = COLOR_GRAY, COLOR_WHITE
     if spec.pens then
-        pen = type(spec.pens) == 'table' and spec.pens[y][x] or spec.pens
+        pen = type(spec.pens) == 'table' and #spec.pens > 0 and (#spec.pens[y] > 0 and spec.pens[y][x] or spec.pens[y]) or spec.pens
```
Comment (myk002) [inline library/lua/gui/widgets.lua:1711]:
```suggestion
        pen = type(spec.pens) == 'table' and safe_index(spec.pens, y, x) or spec.pens[y] or spec.pens
```

Comment (myk002) [reply library/lua/gui/widgets.lua:1711]: to protect against the case where `spec.pens[y]` is `nil`

File: library/lua/gui/widgets.lua [hunk 2]
```diff
@@ -1708,9 +1708,9 @@ end
...
         if spec.pens_hover then
-            pen_hover = type(spec.pens_hover) == 'table' and spec.pens_hover[y][x] or spec.pens_hover
+            pen_hover = type(spec.pens_hover) == 'table' and #spec.pens_hover > 0 and (#spec.pens_hover[y] > 0 and spec.pens_hover[y][x] or spec.pens_hover[y]) or spec.pens_hover
```
Comment (myk002) [inline library/lua/gui/widgets.lua:1713]:
```suggestion
            pen_hover = type(spec.pens_hover) == 'table' and safe_index(spec.pens_hover, y, x) or spec.pens_hover[y] or spec.pens_hover
```

File: library/lua/gui/widgets.lua (hunk 1 above)
Comment (tatoyoda600) [reply library/lua/gui/widgets.lua]: Suggested change tested against all 3 mentioned test cases, all functioning withouth issues

**Review by myk002 — APPROVED** [review]
