### PR TITLE
Fix Items::getDescription

### LINKED ISSUE #5404: Items::getDescription does not display quality correctly
The logic used by the Items module function "getDescription" to display quality levels does not match the game, causing inconsistencies with certain items types.

The game itself does the following:
```
  base_quality = item->getQuality();
  imp_quality = item->getImprovementQuality()
  show_imps = item->isImproved();
  if ((!show_imps) && (base_quality < imp_quality)) {
    base_quality = imp_quality;
  }
```
The result is that "non-displayed" Improvements cause the item's displayed base quality level to be boosted. Such improvements include Thread (on dyed cloth), Cloth (on clothing items), and Prepared Meal Ingredients.

Additionally, the `SHOW_IMP_QUALITY` init flag is not being respected - when not set, this should result in the "outer" quality level being hidden (though it does *not* cause the inner quality level to be boosted, as it was in very old versions before that option was added).

### PR DESCRIPTION
**Pull request by quietust**
* Display correct quality level for items with "non-displayed" improvements
* Add ALL item designations here (and remove "XXwearXX" from other spot)
* Obey SHOW_IMP_QUALITY setting

Fixes #5404

Replaces PR #5406 (which was merging from the wrong branch)

### CODE REVIEW

File: library/modules/Items.cpp [hunk 1]
```diff
@@ -678,14 +679,54 @@ string Items::getDescription(df::item *item, int type, bool decorate) {
...
+
+        // Next, magic enchants
+        if (item->getMagic() != NULL)
+            tmp = '\x11' + tmp + '\x10'; // <| |>
+
+        // Next, improvements
+        if (has_displayed_item_improvements) {
             tmp = '\xAE' + tmp + '\xAF'; // («) + tmp + (»)
-            addQuality(tmp, item->getImprovementQuality());
+            if (df::global::d_init->display.flags.is_set(d_init_flags1::SHOW_IMP_QUALITY))
```
Comment (myk002) [inline library/modules/Items.cpp:702]: although we've traditionally tested globals before using them in the core library, I think this function is well out of the way of the code path that might be hit when globals aren't defined, so this is fine.

**Review by myk002 — APPROVED** [review]
