### PR TITLE
protect against bad values in TranslateName

### LINKED ISSUE #3820: crash on world load in DFHack::Translation::TranslateName
The world is playable without DFHack but with DFHack loaded, it segfaults just after the loading screen for the save finishes and before the fort is displayed.

Happy to help troubleshoot this anyway I can.

Here's the backtrace from gdb.  (linux install, 50.10r1)

```
#0  0x00007fffedd9061b in DFHack::Translation::TranslateName[abi:cxx11](df::language_name const*, bool, bool) () from hack/libdfhack.so
#1  0x00007fffedb012b5 in df::function_identity<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > (*)(df::language_name const*, bool, bool)>::invoke(lua_State*, int) () from hack/libdfhack.so
#2  0x00007fffedadd3be in meta_call_function(lua_State*) () from hack/libdfhack.so
#3  0x00007ffff0b50a1d in luaD_precall(lua_State*, lua_TValue*, int) () from hack/liblua.so
#4  0x00007ffff0b6c6f5 in luaV_execute(lua_State*) () from hack/liblua.so
#5  0x00007ffff0b50cc8 in luaD_callnoyield(lua_State*, lua_TValue*, int) () from hack/liblua.so
#6  0x00007ffff0b513c9 in luaD_pcall(lua_State*, void (*)(lua_State*, void*), void*, long, long) () from hack/liblua.so
#7  0x00007ffff0b45296 in lua_pcallk(lua_State*, int, int, int, long, int (*)(lua_State*, int, long)) () from hack/liblua.so
#8  0x00007fffedae3011 in DFHack::Lua::SafeCall(DFHack::color_ostream&, lua_State*, int, int, bool) () from hack/libdfhack.so
#9  0x00007fffedae7197 in DFHack::Lua::RunCoreQueryLoop(DFHack::color_ostream&, lua_State*, bool (*)(DFHack::color_ostream&, lua_State*, void*), void*) () from hack/libdfhack.so
#10 0x00007fffedaa0316 in DFHack::Core::runCommand(DFHack::color_ostream&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&) () from hack/libdfhack.so
#11 0x00007fffedaa0e22 in DFHack::Core::runCommand(DFHack::color_ostream&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from hack/libdfhack.so
#12 0x00007fffedaf7862 in internal_runCommand(lua_State*) () from hack/libdfhack.so
#13 0x00007ffff0b50a1d in luaD_precall(lua_State*, lua_TValue*, int) () from hack/liblua.so
#14 0x00007ffff0b6c94d in luaV_execute(lua_State*) () from hack/liblua.so
#15 0x00007ffff0b50cc8 in luaD_callnoyield(lua_State*, lua_TValue*, int) () from hack/liblua.so
#16 0x00007ffff0b513c9 in luaD_pcall(lua_State*, void (*)(lua_State*, void*), void*, long, long) () from hack/liblua.so
#17 0x00007ffff0b45296 in lua_pcallk(lua_State*, int, int, int, long, int (*)(lua_State*, int, long)) () from hack/liblua.so
#18 0x00007fffedae3011 in DFHack::Lua::SafeCall(DFHack::color_ostream&, lua_State*, int, int, bool) () from hack/libdfhack.so
#19 0x00007fffedae7197 in DFHack::Lua::RunCoreQueryLoop(DFHack::color_ostream&, lua_State*, bool (*)(DFHack::color_ostream&, lua_State*, void*), void*) () from hack/libdfhack.so
#20 0x00007fffedaa0316 in DFHack::Core::runCommand(DFHack::color_ostream&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&) () from hack/libdfhack.so
#21 0x00007fffedaa0e22 in DFHack::Core::runCommand(DFHack::color_ostream&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from hack/libdfhack.so
#22 0x00007fffedaa1602 in DFHack::Core::loadScriptFile(DFHack::color_ostream&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool) () from hack/libdfhack.so
#23 0x00007fffedaa1daa in loadScriptFiles(DFHack::Core*, DFHack::color_ostream&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from hack/libdfhack.so
#24 0x00007fffedaa24ed in DFHack::Core::handleLoadAndUnloadScripts(DFHack::color_ostream&, DFHack::state_change_event) () from hack/libdfhack.so
#25 0x00007fffedaa437c in DFHack::Core::onStateChange(DFHack::color_ostream&, DFHack::state_change_event) () from hack/libdfhack.so
#26 0x00007fffedaa4d91 in DFHack::Core::doUpdate(DFHack::color_ostream&) () from hack/libdfhack.so
#27 0x00007fffedaa6879 in DFHack::Core::Update() () from hack/libdfhack.so
#28 0x00007ffff7a5ea80 in enablerst::async_loop() () from /home/paudley/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Dwarf Fortress/libg_src_lib.so
#29 0x00007ffff7a5f2d4 in call_loop(void*) () from /home/paudley/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Dwarf Fortress/libg_src_lib.so
#30 0x00007ffff778ba91 in RunThread.lto_priv.0 () from /usr/lib64/libSDL2-2.0.so.0
#31 0x00007ffff6e91259 in ?? () from /lib64/libc.so.6
#32 0x00007ffff6f2661c in ?? () from /lib64/libc.so.6
```

### PR DESCRIPTION
**Pull request by myk002**
Fixes #3820

### CODE REVIEW

File: plugins/autoslab.cpp [hunk 1]
```diff
@@ -212,7 +194,7 @@ static void checkslabs(color_ostream &out)
             )
         {
             createSlabJob(ghost);
-            auto fullName = get_first_name(ghost) + " " + get_last_name(ghost);
+            auto fullName = Translation::capitalize(Translation::TranslateName(&ghost->name, false), true);
```
Comment (lethosor) [inline plugins/autoslab.cpp:197]: I don't think you need `Translation::capitalize()` here, because `addNameWord()` already calls it. If you do find that you need it here, it's worth pointing out that `capitalize(first+last)` isn't equivalent to the previous behavior of `capitalize(first)+capitalize(last)`.

Comment (myk002) [reply plugins/autoslab.cpp]: I think this would have been equivalent since I passed true to have it capitalize every word, but as you point out, it's a noop and can be removed.

File: docs/changelog.txt [hunk 2]
```diff
@@ -60,6 +60,7 @@ Template for new versions:
 
 ## Misc Improvements
 - `dig`: `digtype` command now has options to choose between designating only visible tiles or hidden tiles, as well as "auto" dig mode. Z-level options adjusted to allow choosing z-levels above, below, or the same as the cursor.
+- ``dfhack.TranslateName``: protect against bad language indices added by mods
```
Comment (lethosor) [inline docs/changelog.txt:63]: I would put this under `Fixes` since it's a fix for a crash. Maybe something like:

```suggestion
- ``dfhack.TranslateName()``: fixed crash on certain invalid names, which affected `warn-starving`
```

File: plugins/autoslab.cpp (hunk 1 above)
Comment (lethosor) [reply plugins/autoslab.cpp]: Yeah, missed that, I think you're right.

**Review by lethosor — APPROVED** [review]

**Comment by lethosor** [comment]
Fixes the crash on my end from #3820's save

File: docs/changelog.txt (hunk 2 above)
Comment (myk002) [reply docs/changelog.txt]: Done
