### PR TITLE
dig-now bug fixing

### LINKED ISSUE #2471: dig-now neglects "active" jobs
Active here does not mean the job necessarily has a worker. It means there is a job for the designation, which means the game has removed the designation information from the tile/block and moved it to the job*.

I wrote this as a means of checking if a designation is on the job list
```cpp
class DigJobs {
private:
    std::unordered_map<df::coord, df::tile_dig_designation> designations;
    std::unordered_map<df::coord, df::job*> jobs;
public:
    void load() {
        designations.clear();
        df::job_list_link* node = df::global::world->jobs.list.next;
        while (node) {
            df::job* job = node->item;
            jobs.emplace(job->pos, job);
            node = node->next;
            switch (job->job_type){
                case df::enums::job_type::Dig:
                    designations.emplace(job->pos, df::tile_dig_designation::Default);
                    break;
                case df::enums::job_type::DigChannel:
                    designations.emplace(job->pos, df::tile_dig_designation::Channel);
                    break;
                case df::enums::job_type::CarveRamp:
                    designations.emplace(job->pos, df::tile_dig_designation::Ramp);
                    break;
                case df::enums::job_type::CarveUpwardStaircase:
                    designations.emplace(job->pos, df::tile_dig_designation::UpStair);
                    break;
                case df::enums::job_type::CarveDownwardStaircase:
                    designations.emplace(job->pos, df::tile_dig_designation::DownStair);
                    break;
                case df::enums::job_type::CarveUpDownStaircase:
                    designations.emplace(job->pos, df::tile_dig_designation::UpDownStair);
                    break;
                default:
                    break;
            }
        }
    }
    void remove(const df::coord &pos) {
        if(jobs.count(pos)) {
            Job::removeJob(jobs[pos]);
            auto block = Maps::getTileBlock(pos);
            auto local(pos);
            local.x %= 16;
            local.y %= 16;
#define Coord(id) id.x][id.y
            block->designation[Coord(local)].bits.dig = df::enums::tile_dig_designation::Default;
            block->flags.bits.designated = true;
        }
    }
    df::tile_dig_designation get(const df::coord &pos) {
        if (designations.count(pos)) {
            return designations[pos];
        }
        return df::enums::tile_dig_designation::No;
    }
};
```
With the following integration:
```cpp
                if (jobs.get(pos) || (td.bits.dig != df::tile_dig_designation::No &&
                        !to.bits.dig_marked)) {
                    std::vector<dug_tile_info> dug_tiles;
                    auto designation = jobs.get(pos);
                    jobs.remove(pos);
                    if (designation == df::enums::tile_dig_designation::No) {
                        designation = td.bits.dig;
                    }
                    if (dig_tile(out, map, pos, designation, dug_tiles)) {
```

NOTE: this is only a partial solution, the tile still shows as designated after all is said and done.

### LINKED ISSUE #2720: Dig-now Channel issue
Dig-now seemed to mine instead of channel in this instance. 

image
Recording 2023-01-25 at 16 47 03

### PR DESCRIPTION
**Pull request by cppcooper**
This is a work in progress for dealing with some of the reported issues of dig-now.

PR opened for the artifacts in order to test the changes.

Testing:

- buffered designations implementation resolves #2720
- scans jobs for supported designations
  - looks for valid dig-now positions in the supported jobs
    - cancels valid & supported jobs
    - buffers the designation info
    - should resolve #2471

### CODE REVIEW

File: plugins/dig-now.cpp [hunk 1]
```diff
@@ -26,12 +29,102 @@
...
+                case df::enums::job_type::Dig:
+                    designations.emplace(job->pos, df::tile_dig_designation::Default);
+                    break;
+                case df::enums::job_type::DigChannel:
+                    designations.emplace(job->pos, df::tile_dig_designation::Channel);
+                    break;
+                case df::enums::job_type::CarveRamp:
+                    designations.emplace(job->pos, df::tile_dig_designation::Ramp);
+                    break;
+                case df::enums::job_type::CarveUpwardStaircase:
```
Comment (cppcooper) [inline plugins/dig-now.cpp:100]: This needs to be revised to put together and store `designation` objects, and the switch expanded to include the other designations dig-now cares about.

Comment (myk002) [reply plugins/dig-now.cpp:100]: here's some code I put together while I was investigating this. It's mostly duplicative of what you already have, but it might help a little:
```cpp
static void get_dig_jobs(color_ostream &out,
        std::unordered_map<df::coord, df::job *> &jobs) {
    for (df::job_list_link *link = &world->jobs.list; link; link = link->next) {
        df::job *job = link->item;

        if (!job)
            continue;

        if (job->job_type != df::enums::job_type::Dig &&
                job->job_type != df::enums::job_type::CarveUpwardStaircase &&
                job->job_type != df::enums::job_type::CarveDownwardStaircase &&
                job->job_type != df::enums::job_type::CarveUpDownStaircase &&
                job->job_type != df::enums::job_type::CarveRamp &&
                job->job_type != df::enums::job_type::DigChannel)
            continue;

        jobs.emplace(job->pos, job);
    }
}

df::tile_dig_designation get_dig_job_designation(df::job *job) {
    switch (job->job_type) {
        case df::enums::job_type::Dig:
            return df::tile_dig_designation::Default;
        case df::enums::job_type::CarveUpwardStaircase:
            return df::tile_dig_designation::UpStair;
        case df::enums::job_type::CarveDownwardStaircase:
            return df::tile_dig_designation::DownStair;
        case df::enums::job_type::CarveUpDownStaircase:
            return df::tile_dig_designation::UpDownStair;
        case df::enums::job_type::CarveRamp:
            return df::tile_dig_designation::Ramp;
        case df::enums::job_type::DigChannel:
            return df::tile_dig_designation::Channel;
        default:
           return df::tile_dig_designation::No;
    }
}
```

Comment (myk002) [reply plugins/dig-now.cpp:100]:
```diff
@@ -597,6 +637,9 @@ static void do_dig(color_ostream &out, std::vector<df::coord> &dug_coords,
 
     rng.init();
 
+    std::unordered_map<df::coord, df::job *> jobs;
+    get_dig_jobs(out, jobs);
+
     // go down levels instead of up so stacked ramps behave as expected
     for (int16_t z = options.end.z; z >= options.start.z; --z) {
         for (int16_t y = options.start.y; y <= options.end.y; ++y) {
@@ -608,8 +651,12 @@ static void do_dig(color_ostream &out, std::vector<df::coord> &dug_coords,
 
                 df::coord pos(x, y, z);
                 df::tile_designation td = map.designationAt(pos);
+                df::tile_dig_designation tdd = td.bits.dig;
                 df::tile_occupancy to = map.occupancyAt(pos);
-                if (td.bits.dig != df::tile_dig_designation::No &&
+                if (jobs.count(pos)) {
+                    tdd = get_dig_job_designation(jobs[pos]);
+                }
+                if (tdd != df::tile_dig_designation::No &&
                         !to.bits.dig_marked) {
                     std::vector<dug_tile_info> dug_tiles;
                     if (dig_tile(out, map, pos, td.bits.dig, dug_tiles)) {
```

Comment (myk002) [reply plugins/dig-now.cpp:100]: but of course that doesn't handle the smooth and track cases.

**Comment by myk002** [comment]
while you're in here, could you apply this fix to a typo in that function?
```diff
@@ -631,7 +678,7 @@ static void do_dig(color_ostream &out, std::vector<df::coord> &dug_coords,
                     }
                 } else if (td.bits.smooth == 1) {
                     if (smooth_tile(out, map, pos)) {
-                        to = map.occupancyAt(pos);
+                        td = map.designationAt(pos);
                         td.bits.smooth = 0;
                         map.setDesignationAt(pos, td);
                     }
```

File: plugins/dig-now.cpp (hunk 1 above)
Comment (cppcooper) [reply plugins/dig-now.cpp:100]: Finding the smooth/track info in the job* is my next task. Iirc there is an issue about smoothing designations that may get linked as well.

**Comment by silverwing235** [comment]
PSA: Using Wip in titles currently causes the relevant check to go off the rails (that is, not completing, even when it's found to have been successful) so, maybe move it somewhere else?

**Comment by cppcooper** [comment]
> PSA: Using Wip in titles currently causes the relevant check to go off the rails (that is, not properly completing, even when it's found to have been successful) so, maybe move it somewhere else?

It has been like that as far back as I can remember. I took it as a way of preventing the merge checks from failing, or passing.

**Comment by myk002** [comment]
> > PSA: Using Wip in titles currently causes the relevant check to go off the rails (that is, not properly completing, even when it's found to have been successful) so, maybe move it somewhere else?
> 
> It has been like that as far back as I can remember. I took it as a way of preventing the merge checks from failing, or passing.

this is correct -- the build action works the way it does so it can react promptly when the "WIP" in the title is removed. It hasn't caused warning emails in the past, though, which is a new complication.

File: plugins/dig-now.cpp [hunk 2]
```diff
@@ -339,21 +472,27 @@ static bool dig_tile(color_ostream &out, MapExtras::MapCache &map,
         case df::tile_dig_designation::Channel:
         {
             DFCoord pos_below(pos.x, pos.y, pos.z-1);
+            // todo: does can_dig_channel return false?
```
Comment (myk002) [inline plugins/dig-now.cpp:475]: are you saying the conditions it checks for can never happen here?

File: plugins/dig-now.cpp [hunk 3]
```diff
@@ -26,12 +29,131 @@
...
+                    if (tileSpecial(tt) != df::tiletype_special::SMOOTH) {
+                        td.bits.smooth = 1;
+                    }
+                    break;
+                }
+                case job_type::CarveTrack:
+                    to.bits.carve_track_north = 0 < (job->item_category.whole & 18);
+                    to.bits.carve_track_south = 0 < (job->item_category.whole & 19);
+                    to.bits.carve_track_west = 0 < (job->item_category.whole & 20);
+                    to.bits.carve_track_east = 0 < (job->item_category.whole & 21);
```
[the remark this answers is not in the document]
Comment (cppcooper) [reply plugins/dig-now.cpp:129]: Right, I forgot to shift. I knew I needed to, and just didn't

File: plugins/dig-now.cpp [hunk 4]
```diff
@@ -26,12 +29,131 @@
...
+private:
+    std::unordered_map<df::coord, designation> designations;
+    std::unordered_map<df::coord, df::job*> jobs;
+public:
+    void load(MapExtras::MapCache &map) {
+        designations.clear();
+        df::job_list_link* node = df::global::world->jobs.list.next;
+        while (node) {
+            df::job* job = node->item;
+            if(!Maps::isValidTilePos(job->pos))
```
[the remark this answers is not in the document]
Comment (cppcooper) [reply plugins/dig-now.cpp:89]: Probably. Thought I had started it at the non null node/item

File: plugins/dig-now.cpp (hunk 2 above)
Comment (cppcooper) [reply plugins/dig-now.cpp:475]: It is a todo. But I would infer from there being a designation, that it can be channeled.

File: plugins/dig-now.cpp [hunk 5]
```diff
@@ -26,12 +29,131 @@
...
+                continue;
+
+            jobs.emplace(job->pos, job);
```
[the remark this answers is not in the document]
Comment (cppcooper) [reply plugins/dig-now.cpp:92]: Carelessness. It definitely should just be the ones with designations stored

File: plugins/dig-now.cpp [hunk 6]
```diff
@@ -26,12 +29,131 @@
...
+// Debugging
+namespace DFHack {
+    DBG_DECLARE(dignow, general, DebugCategory::LINFO);
+    DBG_DECLARE(dignow, channels, DebugCategory::LINFO);
+}
+
+#define COORD "%" PRIi16 " %" PRIi16 " %" PRIi16
+#define COORDARGS(id) id.x, id.y, id.z
+
+// todo: integrate logging for debugging the layered channel problem
```
[the remark this answers is not in the document]
Comment (cppcooper) [reply plugins/dig-now.cpp:49]: No doubt. I didn't even end up reading the log stuff I added

**Review by myk002 — APPROVED** [review]

**Comment by myk002** [comment]
could you add changelog entries for these fixes?

**Comment by myk002** [comment]
this is causing strange lockups in my testing, so reverting for now while we investigate. I'll reopen the attached bugs.
