### PR TITLE
fix labor inferences for custom furnaces [labormanager,WIP]

### LINKED ISSUE #1595: labormanager doesn't adduce correct build labor for custom furnaces
I got a report via Discord of labormanager failing to allocate an architect to build a Masterwork "finishing forge". On research, I've determined that this is a custom furnace. Labormanager is not respecting the designated custom build labor when inferring the required build labor, which results in starving finishing forges (and likely other Masterwork custom furnaces) of the architect required.

### PR DESCRIPTION
**Pull request by ab9rf**
Also clean up how paved roads are handled (the way it was was stupid)

fixes #1595 

WIP b/c not tested yet

### CODE REVIEW

File: plugins/labormanager/joblabormapper.cpp [hunk 1]
```diff
@@ -313,14 +311,27 @@ class jlfunc_construct_bld : public jlfunc
                 return workshop_build_labor[ws->type];
         }
         break;
+        case df::building_type::Furnace:
+        {
+            df::building_furnacest* frn = (df::building_furnacest*) bld;
```
Comment (lethosor) [inline plugins/labormanager/joblabormapper.cpp:316]: Maybe `virtual_cast` would be safer?

File: plugins/labormanager/joblabormapper.cpp [hunk 2]
```diff
@@ -313,14 +311,27 @@ class jlfunc_construct_bld : public jlfunc
...
+            if (frn->design && !frn->design->flags.bits.designed)
+                return df::unit_labor::ARCHITECT;
+            if (frn->type == df::furnace_type::Custom)
+            {
+                df::building_def* def = df::building_def::find(frn->custom_type);
+                return def->build_labors[0];
+            }
+            else
+                // cast to building_actual should be safe here because at this point the building has been designed
+                return construction_build_labor((df::building_actual*)bld);
```
Comment (lethosor) [inline plugins/labormanager/joblabormapper.cpp:326]: Also, building_furnacest inherits from building_actual, so you could probably pass in `frn` here without needing the cast

File: plugins/labormanager/joblabormapper.cpp (hunk 1 above)
Comment (ab9rf) [reply plugins/labormanager/joblabormapper.cpp:316]: Probably. There are a ton of "potentially unsafe" casts in this code. If I "fix" this one, I should probably fix the one that's like ten lines above it in the code for custom workshops, too...

Comment (lethosor) [reply plugins/labormanager/joblabormapper.cpp:316]: Fair, I didn't expand the diff here. `virtual_cast` would check the actual type, but in any case, this should only ever break due to a structures issue (e.g. a new building_type added somewhere in the middle), which would be pretty easy to catch since it would break a lot of other things too.

Comment (ab9rf) [reply plugins/labormanager/joblabormapper.cpp:316]: Also, `virtual_cast` isn't really safer here. All `virtual_cast` is is a wrapper that either casts the pointer to the type or returns null. The code still has to do a null check. But (with current DF structures, at least) we're guaranteed that if `bld->getType()` is Furnace, then `bld` is a `building_furnacest`.

Comment (lethosor) [reply plugins/labormanager/joblabormapper.cpp:316]: virtual_cast also checks DF's type information (not sure if that's what you meant; it's basically dynamic_cast, but we can't use that for DF-defined types). That's based on the `<vtable-address>` entries in symbols.xml, which are a bit more reliable than our enum definitions. But in order for this code to fail, a new building subclass would need to be added whose `getType()` returns what was previously `building_type::Furnace`, and our  `building_type` would need to be outdated, which should really only be possible soon after a DF release. So I agree, it's not really worth changing.

**Comment by lethosor** [comment]
Fine with me if you merge this once you're satisfied that it works (I figure you have a better idea of how to test it)

**Comment by lethosor** [comment]
@ab9rf does this one still just need to be tested? I can make an attempt at that if needed.

**Comment by ab9rf** [comment]
Sorry, I haven't had the opportunity to look at this yet.

**Comment by lethosor** [comment]
I played around with it. Building and destroying a custom furnace in the save from #1595 (thanks, @Tokeli!) seemed to work. However, in that save and in a clean embark, I couldn't get a paved road built. In the former, it got designed, but the one road builder never built it, and in the latter, it never even got designed (nobody wound up with architecture enabled after a few in-game days). I'm not very familiar with labormanager, and I haven't tested whether this happened before this PR yet, but I could be doing something wrong.

**Comment by lethosor** [comment]
Yeah, this seems to break paved roads. I was able to get them built in a fresh save before merging these changes, but not after. Not a huge deal - I suspect rolling back the road-related changes here will fix it. I'll try that tomorrow.

File: plugins/labormanager/joblabormapper.cpp [hunk 3]
```diff
@@ -334,6 +345,8 @@ class jlfunc_construct_bld : public jlfunc
             return construction_build_labor(b);
         }
         break;
+        case df::building_type::RoadPaved:
+            return df::unit_labor::BUILD_ROAD;
```
Comment (lethosor) [inline plugins/labormanager/joblabormapper.cpp:349]: I think this is the issue - paved roads require architects, which the old case handled. I'll see if that fixes it.
