### PR TITLE
exclude nonclothing from tailor's scan

### LINKED ISSUE #4023: Crash in Tailor::scan_replacements()
Just playing, i'm having a crash from time to time, getting more frequent.
Here is the backtrace taken from the core dump in linux:
```

Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f195ef87350 in Tailor::scan_replacements() () from /home/dleite/Steam/steamapps/common/Dwarf Fortress/hack/plugins/tailor.plug.so
[Current thread is 1 (Thread 0x7f197ff676c0 (LWP 459))]
(gdb) bt
#0  0x00007f195ef87350 in Tailor::scan_replacements() () from /home/dleite/Steam/steamapps/common/Dwarf Fortress/hack/plugins/tailor.plug.so
#1  0x00007f195ef840b7 in do_cycle(DFHack::color_ostream&) () from /home/dleite/Steam/steamapps/common/Dwarf Fortress/hack/plugins/tailor.plug.so
#2  0x00007f195ef8461e in plugin_onupdate () from /home/dleite/Steam/steamapps/common/Dwarf Fortress/hack/plugins/tailor.plug.so
#3  0x00007f195f9ac71e in DFHack::PluginManager::OnUpdate(DFHack::color_ostream&) () from hack/libdfhack.so
#4  0x00007f195f893f66 in DFHack::Core::onUpdate(DFHack::color_ostream&) () from hack/libdfhack.so
#5  0x00007f195f8a66b3 in DFHack::Core::doUpdate(DFHack::color_ostream&) () from hack/libdfhack.so
#6  0x00007f195f8a8169 in DFHack::Core::Update() () from hack/libdfhack.so
#7  0x00007f198145ac10 in enablerst::async_loop() () from /home/dleite/Steam/steamapps/common/Dwarf Fortress/libg_src_lib.so
#8  0x00007f198145b464 in call_loop(void*) () from /home/dleite/Steam/steamapps/common/Dwarf Fortress/libg_src_lib.so
#9  0x00007f19812bf3e5 in ?? () from /usr/lib64/libSDL2-2.0.so.0
#10 0x00007f198136e039 in ?? () from /usr/lib64/libSDL2-2.0.so.0
#11 0x00007f1980a92cc2 in start_thread () from /lib64/libc.so.6
#12 0x00007f1980b1e228 in clone3 () from /lib64/libc.so.6
(gdb)
```

i will try to to mess with tailor tasks to see if i can workaround any error in there, but no idea what is happening

### PR DESCRIPTION
**Pull request by ab9rf**
also add a bounds check for item makerrace

should fix #4023

### CODE REVIEW

File: plugins/tailor.cpp [hunk 1]
```diff
@@ -288,9 +291,17 @@ class Tailor {
...
+                // skip armor
+                if (w->getEffectiveArmorLevel() > 0)
+                    continue;
+
                 auto ty = w->getType();
 
-                int isize = world->raws.creatures.all[w->getMakerRace()]->adultsize;
+                auto makerRace = w->getMakerRace();
+                if (makerRace < 0 || makerRace >= (int16_t) world->raws.creatures.all.size())
+                    continue;
```
Comment (myk002) [inline plugins/tailor.cpp:302]: could use `vector_get` for this, but no need to change now.

**Review by myk002 — COMMENTED** [review]
needs changelog entry
